import { StyleSheet } from "react-native";
import { color } from "./colors";
import { RFValue } from "react-native-responsive-fontsize";
export default CommonStyle = StyleSheet.create({
  mainScreen: { flex: 1, backgroundColor: color.white },
  button: {
    borderRadius: RFValue(5),
    justifyContent: "center",
    alignItems: "center",
  },
  shadow: {
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  bottomShadow: {
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 1,
    shadowOffset: { width: 0, height: 1 },
  },
  btnBoxBackground: {
    borderRadius: RFValue(5),
    backgroundColor: color.white,
    height: RFValue(30),
    width: RFValue(30),
    justifyContent: "center",
    alignItems: "center",
  },
  text1: {
    fontSize: RFValue(16),
    fontWeight: "700",
    fontFamily: "SFProText-Regular",
    letterSpacing: 0.6,
    color: color.cod_gray,
  },
  text2: {
    fontSize: RFValue(14),
    fontWeight: "400",
    fontFamily: "SFProText-Regular",
    letterSpacing: 0.6,
    color: color.cod_gray,
  },
  text3: {
    fontSize: RFValue(12),
    fontWeight: "400",
    fontFamily: "SFProText-Regular",
    color: color.cod_gray,
  },
  btnText1: {
    fontSize: RFValue(14),
    fontWeight: "700",
    fontFamily: "SFProText-Regular",
    letterSpacing: 0.6,
    color: color.cod_gray,
  },
  btnText2: {
    fontSize: RFValue(12),
    fontWeight: "700",
    fontFamily: "SFProText-Regular",
    letterSpacing: 0.6,
    color: color.cod_gray,
  },
  errTextStyle: {
    fontSize: RFValue(10),
    fontWeight: "400",
    fontFamily: "SFProText-Regular",
    color: color.red,
  },
  headerContainer: {
    marginTop: RFValue(30),
    paddingHorizontal: RFValue(20),
  },
  container: {
    marginBottom: RFValue(80),
    borderRadius: RFValue(8),
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 1.5 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 5,
    paddingTop: RFValue(12),
    paddingBottom: RFValue(12),
  },
  dialogHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: RFValue(15),
    paddingRight: RFValue(15),
    marginBottom: RFValue(12),
  },
  horizontalLine: {
    borderBottomWidth: 0.6,
    borderBottomColor: color.wild_blue,
    width: "94%",
  },
  bottomText: {
    textDecorationLine: "underline",
    color: color.white,
    fontSize: RFValue(10),
    fontFamily: "SFProText-Regular",
    textAlign: "center",
  },
  subTitle: {
    fontWeight: "700",
    fontSize: RFValue(10),
    fontFamily: "SFProText-Regular",
    color: color.cod_gray,
  },
  modalBackground: {
    flex: 1,
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
    backgroundColor: "rgba(100,100,100, 0.8)",
    width: "100%",
  },
  forgotText: {
    fontSize: RFValue(10),
    color: color.cod_gray,
    fontWeight: "400",
    textDecorationLine: "underline",
  },
  errText: {
    fontSize: RFValue(11),
    fontWeight: "400",
    fontFamily: "SFProText-Regular",
    color: color.red,
  },
  selectedRadioText: {
    color: color.white,
  },
  buttonStyle: {
    height: RFValue(50),
  },
  radioTextStyle: {
    fontWeight: "400",
    fontFamily: "SFProText-Regular",
    fontSize: RFValue(10),
    textAlign: "center",
    flexWrap: "wrap",
  },
  radioContainer: {
    backgroundColor: color.white,
    borderRadius: RFValue(5),
    marginLeft: -3,
  },
  dropdown: {
    height: 55,
    borderRadius: RFValue(5),
    padding: RFValue(8),
    opacity: 0.5,
  },
  dropdowText: { fontSize: RFValue(10), color: color.cod_gray },
  iconStyle: { height: RFValue(12), width: RFValue(12) },
});
